import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CarContext } from "@/app/context/carContext";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mandadi-top App",
  description: "Generated by Julián Ontiveros",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CarContext>
          <MantineProvider>{children}</MantineProvider>
        </CarContext>
      </body>
    </html>
  );
}
