import "./globals.css";
import { CarContext } from "@/app/context/carContext";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

export const metadata = {
  title: "Mandadi-top App",
  description: "Generated by Julián Ontiveros",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CarContext>
          <MantineProvider>{children}</MantineProvider>
        </CarContext>
      </body>
    </html>
  );
}